import "@/styles/globals.css";

export const metadata = {
  title: "学生实习管理系统",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta name="description" content="Generated by create next app" />
        <meta charSet="utf-8" />
        <link rel="icon" href="/logo.png" />
      </head>
      <body className="bg-white">{children}</body>
    </html>
  );
}
